apiName: PenpotApi
outputDir: build
generatorName: csharp
library: unityWebRequest
packageName: Ordinary.Core.PenpotApi
templateDir: template
additionalProperties:
  validatable: "false"
  targetFramework: netstandard2.1
  skipFormModel: false
  supportsFileParameters: true
  nullableReferenceTypes: false
  useOneOfDiscriminatorLookup: true
globalProperties:
  debugModels: true
  debugOperations: true
  skipFormModel: false
